[package]
name = "fotia"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.9.0"
bytemuck = "1.22.0"
parking_lot = "0.12.3"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[target.'cfg(windows)'.dependencies]
oxidx = { git = "https://github.com/if0ne/oxidx" }
